version: '3.8'

services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: Change_Here
            MYSQL_USER: miekaji
            MYSQL_PASSWORD: Change_Here2

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www/html
        depends_on:
            - php

    php:
        build: ./php
        volumes:
            - ./www:/var/www/html
        depends_on: 
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        depends_on: 
            - db